// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Obra struct {
	ID           int32          `json:"id"`
	Titulo       string         `json:"titulo"`
	Descripcion  sql.NullString `json:"descripcion"`
	Artista      string         `json:"artista"`
	FechaIngreso time.Time      `json:"fecha_ingreso"`
	Precio       string         `json:"precio"`
	Vendida      sql.NullBool   `json:"vendida"`
}
